# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plotI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PlotI(object):
    def setupUi(self, PlotI):
        PlotI.setObjectName("PlotI")
        PlotI.resize(400, 300)
        self.pushButton = QtWidgets.QPushButton(PlotI)
        self.pushButton.setGeometry(QtCore.QRect(20, 10, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.graphicsView = QtWidgets.QGraphicsView(PlotI)
        self.graphicsView.setGeometry(QtCore.QRect(25, 51, 331, 221))
        self.graphicsView.setObjectName("graphicsView")

        self.retranslateUi(PlotI)
        QtCore.QMetaObject.connectSlotsByName(PlotI)

    def retranslateUi(self, PlotI):
        _translate = QtCore.QCoreApplication.translate
        PlotI.setWindowTitle(_translate("PlotI", "Plot-I"))
        self.pushButton.setText(_translate("PlotI", "Get I "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PlotI = QtWidgets.QWidget()
    ui = Ui_PlotI()
    ui.setupUi(PlotI)
    PlotI.show()
    sys.exit(app.exec_())
